FROM node:20
WORKDIR /usr/src/app
COPY . .

# Environment variable
ENV DATABASE_URL=
ENV NEXTAUTH_SECRET=
ENV DEV_COOKIE_NAME=
ENV COOKIE_NAME=
ENV DOMAIN=
# OAuth credentials
ENV GITHUB_ID=
ENV GITHUB_SECRET=
ENV GOOGLE_ID=
ENV GOOGLE_SECRET=
# Cloudinary credentials
ENV NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET=
ENV NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=
ENV NEXT_PUBLIC_CLOUDINARY_URL=

ENV NODE_ENV = 

# Commands
RUN npm install
RUN npm run build

CMD ["npm", "start"]

EXPOSE 3000
